# This is a basic workflow to help you get started with Actions

name: publish blazor webApp
env:
  PUBLISH_DIR: bin/Release/net5.0/publish/wwwroot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Publish dotnet app
        run: dotnet publish -c Release

      - name: rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with: 
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: REPOSITORY_NAME
          
      - name: Add .nojekyll
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
        
      - name: Commit to GitHub pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: main
          build_dir: ${{ env.PUBLISH_DIR }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
